### ISSUE TITLE
[BUG] CentOS Linux 7.9 - set up Vault repos

### ISSUE THREAD

**Issue by bocekm** [EuroLinux/cloud-images-rfc#11]
**Describe the bug**
The CentOS 7.9 box uses non-functioning repos. Since CentOS 6 has been retired, the original standard repos has been archived in the Vault (https://vault.centos.org/6.10/).

**Cloud Image**
Vagrant, libvirt, eurolinux-vagrant/centos-7 box version 7.9.62 https://app.vagrantup.com/eurolinux-vagrant/boxes/centos-7/versions/7.9.62

**To Reproduce**

1. Vagrantfile:
```
Vagrant.configure("2") do |config|
  config.vm.box = "eurolinux-vagrant/centos-7"
end
```
1. `vagrant up`
1. `vagrant ssh`
1. run `sudo yum update` in the box
1. See error:
```
Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock error was
14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error
<snip>
Cannot find a valid baseurl for repo: base/7/x86_64
```

**Expected behavior**
The box starts up and I am able to install packages through yum.

**Additional context**
The original CentOS repos need to be edited for example using these commands to use the Vault:
```
sed -i 's/^mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-Base.repo
sed -i 's/^#baseurl.*$/baseurl=http:\/\/vault.centos.org\/7.9.2009\/os\/x86_64/g' /etc/yum.repos.d/CentOS-Base.repo 
```

Similar issues:
- https://github.com/EuroLinux/cloud-images-rfc/issues/4
- https://github.com/EuroLinux/cloud-images-rfc/issues/6

**Comment by AlexBaranowski** [comment]
@bocekm I will personally change it today/tomorrow for the following images:

- CentOS 7
- EuroLinux 7
- Scientific Linux 7
- Oracle Linux 7 (They are not changing repos if I recall correctly, it's smart).

Thank you for your report 👍🏻 !

**Comment by AlexBaranowski** [comment]
@bocekm all el7 Vagrant boxes were fixed.
