### ISSUE TITLE
Vagrant Tiimeout libvirt amd64

### ISSUE THREAD

**Issue by davidpaige** [EuroLinux/cloud-images-rfc#13]
I am not doing very well with Vagrant on Fedora.  I'm usually pretty good with tech, but I've tried several Vagrant files and none of them work for me.  Any idea what I'm doing wrong here?

I followed the instructions to download the amd64 registry, but I'm not really sure what to do with if after I download it.  I replaced the Vagrant file as indicated, and I get a timeout.

Thank you for any help you can provide.

vagrant up
Bringing machine 'default' up with 'libvirt' provider...
==> default: Checking if box 'eurolinux-vagrant/centos-stream-9' version '9.0.48' is up to date...
==> default: Creating image (snapshot of base box volume).
==> default: Creating domain with the following settings...
==> default:  -- Name:              vagrant-rhcsa_default
==> default:  -- Description:       Source: /home/lion/Documents/vagrant-rhcsa/Vagrantfile
==> default:  -- Domain type:       kvm
==> default:  -- Cpus:              1
==> default:  -- Feature:           acpi
==> default:  -- Feature:           apic
==> default:  -- Feature:           pae
==> default:  -- Clock offset:      utc
==> default:  -- Memory:            512M
==> default:  -- Base box:          eurolinux-vagrant/centos-stream-9
==> default:  -- Storage pool:      default
==> default:  -- Image(vda):        /home/lion/.local/share/libvirt/images/vagrant-rhcsa_default.img, virtio, 80G
==> default:  -- Disk driver opts:  cache='default'
==> default:  -- Graphics Type:     vnc
==> default:  -- Video Type:        cirrus
==> default:  -- Video VRAM:        16384
==> default:  -- Video 3D accel:    false
==> default:  -- Keymap:            en-us
==> default:  -- TPM Backend:       passthrough
==> default:  -- INPUT:             type=mouse, bus=ps2
==> default: Creating shared folders metadata...
==> default: Starting domain.
==> default: Domain launching with graphics connection settings...
==> default:  -- Graphics Port:      5900
==> default:  -- Graphics IP:        127.0.0.1
==> default:  -- Graphics Password:  Not defined
==> default:  -- Graphics Websocket: 5700
==> default: Waiting for domain to get an IP address...
==> default: Waiting for machine to boot. This may take a few minutes...
==> default: Removing domain...
==> default: Deleting the machine folder
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.

**Comment by AlexBaranowski** [comment]
Howdy,

First of all, have you installed the vagrant from Fedora repositories or from the official hashicorp repository?

How do you check it?

```
sudo yum list installed vagrant

Installed Packages
vagrant.noarch                                                                              2.3.4-5.fc40                                                                               @fedora
```

If there is @fedora, you are good.

Then, the next question is, how did you install the libvirt plugin?

Once more, it can be installed from Fedora repositories.

```
sudo dnf list installed vagrant-libvirt
```

```
Alex@salarian-vessel > sudo yum list installed vagrant-libvirt
Installed Packages
vagrant-libvirt.noarch                                                                          0.11.2-3.fc40                                                                          @fedora
```

Next, let's check your CPU with `lcspu` -> there must be a `vmx` flag (INTEL):

```
lscpu | grep vmx
```

or `svm` for AMD CPUs

```
lscpu | grep svm
```

You can also provide me with info about your CPU -> Example
```
Alex@salarian-vessel ~> lscpu | grep -i 'model name'
Model name:                           12th Gen Intel(R) Core(TM) i7-1260P
```

Also you can check the libvirt machnines with `virt-manager`.

EDIT: I'm old that's why I'm still writing `yum` instead of `dnf`

**Comment by davidpaige** [comment]
Thank you for the reply.  I'm old school too.  yum will always work just like dnf.

I did use the fedora packages.
```
rpm -qa|grep vagrant
vagrant-libvirt-0.11.2-3.fc40.noarch
vagrant-2.3.4-6.fc41.noarch
```
svm is present.
```
lscpu|grep svm
Flags:                                <snip> cmp_legacy svm extapic <snip>lbrv svm_lock nrip_save <snip>
```
Here is my cpu info
```
lscpu | grep -i 'model name'
Model name:                           AMD Ryzen 7 7840U w/ Radeon  780M Graphics
```
The virtual machines aren't showing up in virt-manager.  It seems like it shouldn't be this difficult.

**Comment by AlexBaranowski** [comment]
Can you check if your user is in libvirt group?

```
Alex@salarian-vessel ~> groups
Alex wheel stapusr docker libvirt
```
My user is in `Alex` ... and `libvirt`

**Comment by AlexBaranowski** [comment]
Also, your vagrant-libvirt package is from Fedora 40 and your vagrant package is from Fedora 41.

I checked there and there is vagrant-libvirt for Fedora 41 -> https://ftp.icm.edu.pl/pub/Linux/fedora/linux/development/41/Everything/x86_64/os/Packages/v/

Please run `dnf update` and check if both of packages has same dist tag (f40, f41 -> f41, f41) after update.

**Comment by AlexBaranowski** [comment]
@davidpaige
It's been the week.

I managed to show at least a few places that might require fixing, mostly mixing the Fedora 40 and Fedora 41 packages. I'm closing the issue as it's not directly connected with the provided images.

I hope that you find a solution.
Best,
Alex
