### ISSUE TITLE
[BUG] Box dumped to OVA not running in VMware

### ISSUE THREAD

**Issue by xx-zhang** [EuroLinux/cloud-images-rfc#5]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

box dunmpd as ova than  i push it to ova by vmware or exsi to generate a virtulmachine, but not run as i expected .

![image](https://user-images.githubusercontent.com/47806549/120766582-f398dd00-c54c-11eb-922d-11fce0012f24.png)

**Additional context**

**Comment by AlexBaranowski** [comment]
Could you provide the following information:

- Which vagrant box is problematic?
- Which VMWare version are you using?

We build and test our VM's on VMware Workstation, so we never tested them on vSphere on anything like that. Still, I might try getting a proper license/environment to test it.

**Comment by AlexBaranowski** [comment]
@xx-zhang Could you provide more information? It would greatly help us to determine what might be wrong. Without this I will have to close this task as unresolved 😭 .

**Comment by AlexBaranowski** [comment]
Hi,

Because there is no feedback. I have to close this issue.

Feel free to create new one with more context.
